version: "3"
services:

  phpapp:
    image: php:7-fpm
    volumes: 
      - ./app:/usr/share/nginx/html

  appnginx:
    build:
      context: ./conf/nginx
      dockerfile: Dockerfile-nginx
    volumes:
      - ./app:/usr/share/nginx/html
    links: 
      - phpapp
    ports:
      - 80:80
